fix: fixed the bug of incorrect titles
Filmaro/Filmaro pull request #16
Opened 2022-06-08 23:55 UTC by JoaoWudarski

# 🎬 Filmaro 🎬 - Pull Request

## Description:

Corrigido bug ao mostrar titulos

## Type of change:

- [ ] New feature (This PR adds a new functionality to the project)
- [x] Bug fix (This PR covers solving a bug)
- [ ] Documentation (This PR require a documentation update, i.e. the class doc)
- [ ] Issue resolution (This PR solve an github open issue)
[Link to solved Issue](#IssueLinkGoesHere)

## Checklist:

Delete this message and the options that is unnecessary, i.e. the options that are no relate to the changes you made.

- [ ] I followed the concept of clean code.
- [ ] My changes do not generate a new warning or issue.
- [x] I deleted all the code lines that are not being used.
- [ ] I commented my code in some areas i believed that are difficult to understand.
- [ ] I have made corresponding changes to the documentation.
- [ ] I create a release tag in case my changes is a breaking-change.

👩🏽‍💻~ Filmaro Team ~👨🏽‍💻

2022-06-08 23:59 UTC, Im0tec requested changes

2022-06-08 23:59 UTC, Im0tec commented on src/components/TitlePage/TitlePage.js
> +    console.log(movie);
Tem que tirar isso aqui ow

2022-06-09 00:19 UTC, JoaoWudarski commented on src/components/TitlePage/TitlePage.js
> +    console.log(movie);
Feito!

2022-06-09 00:20 UTC, Im0tec approved these changes

2022-06-09 00:21 UTC, merged