Feature/dropdown categories
Filmaro/Filmaro pull request #34
Opened 2022-07-26 20:09 UTC by MatheusFrate

# 🎬 Filmaro 🎬 - Pull Request

## Description:

Added functionality to "Categorias" button so users can navigate through the available options to search movies or tv series with the given genres searched.
Added a "back" button in TitlePage
Stopped the request looping in some pages

## Type of change:

- [x] New feature (This PR adds a new functionality to the project)
- [ ] Technical debt (This PR improve features already created)
- [x] Bug fix (This PR covers solving a bug)
- [ ] Documentation (This PR require a documentation update, i.e. the class doc)
- [x] Issue resolution (This PR solve an github open issue)
[Link to solved Issue](#IssueLinkGoesHere)

## Checklist:

- [x] My changes do not generate a new warning or issue.

👩🏽‍💻~ Filmaro Team ~👨🏽‍💻

2022-07-26 22:35 UTC, Im0tec requested changes
Niceee job 💥
I made some observations about the translation and a suggestion about the dropdown, other than that, it's all great.

2022-07-26 22:35 UTC, Im0tec commented on src/App.js
> +        <Route path='/search/:filter/:genderName/:id' element={<FilterTitles/>}/>
**Gender** é gênero tipo homem, mulher, trans, não-binário.
O certo aqui é **Genre**, então precisa renomear parar `:genreName`

2022-07-26 22:35 UTC, Im0tec commented on src/components/FilterTitles/FilterTitles.js
> +  const { filter, id, genderName } = useParams();
O mesmo aqui, deve ser renomeado para `genreName`.

2022-07-26 22:35 UTC, Im0tec commented on src/components/FilterTitles/FilterTitles.js
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
Por que desativou o lint? 😳

2022-07-26 22:35 UTC, Im0tec commented on src/components/FilterTitles/FilterTitles.js
> +        getMovies(id ? `FILMES - ${genderName} ` : 'FILMES');
Mudar pra `genreName`.

2022-07-26 22:35 UTC, Im0tec commented on src/components/FilterTitles/FilterTitles.js
> +        getSeries(id ? `SÉRIES - ${genderName} ` : 'SÉRIES');
Mudar pra `genreName`.

2022-07-26 22:35 UTC, Im0tec commented on src/components/Header/Header.js
> +    if(isFirstRender.current) {
mds a gambiarra kkkkkkkkkkkkkkkk @JoaoWudarski 🙏🏽🙏🏽

2022-07-26 22:35 UTC, Im0tec commented on src/components/Header/Header.js
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
Paaara de desativar o lint 😳😳😳

2022-07-26 22:35 UTC, Im0tec commented on src/index.js
> +  // <React.StrictMode>
Se ta funfando sem, pode tirar o comentário e apagar mesmo.

2022-07-26 22:35 UTC, Im0tec commented on src/components/Header/style.css
> +.dropdown {
Eu acho que seria legal colocar a cor roxa do Filmaro no fundo do dropdown, o que você acha?

2022-07-27 12:52 UTC, JoaoWudarski commented on src/components/FilterTitles/FilterTitles.js
>    }
Será que não é melhor deixar a linha 42 direto onde essa função é chamada? Porque a linha 43 não é genérica... E você está setando duas vezes, não está? Uma na 43 e outra na 33/21

2022-07-27 12:52 UTC, JoaoWudarski commented on src/components/Header/Header.js
> +    if(isFirstRender.current) {
Tô quebrando a cabeça para entender o que essa função está fazendo kkkkkkkkkkkkkk

2022-07-27 12:52 UTC, JoaoWudarski commented on src/App.js
> +        <Route path='/search/:filter/:genderName/:id' element={<FilterTitles/>}/>
Não binário não é gênero!

2022-07-27 12:52 UTC, JoaoWudarski commented on src/components/Homepage/Home/Home.js
> +  },[]);
Talvez isso resolva o bo dos requests, mas ela é barrada na esteira por não conseguir compilar kkkkkk Vamos descobrir

2022-07-27 12:52 UTC, JoaoWudarski commented on src/components/TitlePage/TitlePage.js
> +          <FiArrowLeft className='backButton' onClick={() => window.location.href='/home'}/>
Vou dar uma pesquisada também, mas não tem como voltar para a página que estava ao invés de voltar para o home?

2022-07-27 12:52 UTC, JoaoWudarski commented on src/index.js
> +  // <React.StrictMode>
SóAgradece

2022-07-27 12:52 UTC, JoaoWudarski commented on src/components/FilterTitles/FilterTitles.js
> +  const getMovies = async (t) => {
O que caralhos é t? KKKKKKKKK Clean code tomou um tiro de doze aqui

2022-07-27 12:52 UTC, JoaoWudarski commented on src/App.js
> +        <Route path='/search/:filter/:genderName/:id' element={<FilterTitles/>}/>
Dependendo da complexidade, acho que ficaria melhor o resource ser /search/:filter/categories/:id. Da muito trabalho fazer isso?

2022-07-27 12:52 UTC, JoaoWudarski commented on src/components/FilterTitles/FilterTitles.js
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
O que é esse lint?

2022-07-27 12:52 UTC, JoaoWudarski commented on src/components/Header/style.css
> +.dropdown {
Sogrinha

2022-07-27 12:59 UTC, Im0tec commented on src/components/TitlePage/TitlePage.js
> +          <FiArrowLeft className='backButton' onClick={() => window.location.href='/home'}/>
Tem sim, vou atualizar. Eu tinha pensado nisso na hora, porém eu tinha esquecido que existem outros caminhos para se chegar na página de um título, além da Home.

2022-07-27 13:22 UTC, Im0tec commented on src/components/TitlePage/TitlePage.js
> +          <FiArrowLeft className='backButton' onClick={() => window.location.href='/home'}/>
Arrumado!

2022-07-27 14:26 UTC, Im0tec commented on src/components/FilterTitles/FilterTitles.js
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
o lint analisa erros de indentação e má formatação do código

2022-07-27 14:27 UTC, JoaoWudarski commented on .github/workflows/filmaro-pr.yml
> +name: Filmaro CI
Done!

2022-07-27 14:27 UTC, Im0tec commented on src/App.js
> +        <Route path='/search/:filter/:genderName/:id' element={<FilterTitles/>}/>
cade o banheiro?

![image](https://user-images.githubusercontent.com/69486662/181272889-caf1b82b-1139-4186-99be-2bea9e8f637d.png)

2022-07-27 14:28 UTC, JoaoWudarski commented on src/components/FilterTitles/FilterTitles.js
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
Para de desativar o lint @TETEUS

2022-07-27 17:03 UTC, MatheusFrate commented on src/App.js
> +        <Route path='/search/:filter/:genderName/:id' element={<FilterTitles/>}/>
tu viu o reencontro dela com o chard?

2022-07-27 17:09 UTC, MatheusFrate commented on src/components/FilterTitles/FilterTitles.js
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
![image](https://user-images.githubusercontent.com/55608318/181307760-d4af7eff-f797-462e-beeb-1b795c264af8.png)

2022-07-27 17:11 UTC, MatheusFrate commented on src/components/Header/Header.js
> +    if(isFirstRender.current) {
ela vê se é a primeira renderização, então se o current for true, eu coloco como falso, para ele não rodar mais de uma vez essa parte

2022-07-27 17:11 UTC, JoaoWudarski commented on src/components/FilterTitles/FilterTitles.js
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
Não fui eu, não fui eu

2022-07-27 17:18 UTC, MatheusFrate commented on src/components/FilterTitles/FilterTitles.js
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
putz, então fui enganado pelo git, malz por duvidar do senhor

2022-07-27 17:45 UTC, MatheusFrate commented on src/components/FilterTitles/FilterTitles.js
>    }
é que depende da chamada, se ele entrou no getbyGenres, ele não vai rodar o set do getSeries.
lá seria uma busca de todos as series, ai ele busca só as series/filmes que tem o genero especificado

2022-07-27 17:45 UTC, MatheusFrate commented on src/components/Homepage/Home/Home.js
> +  },[]);
ai complica kkkkk

2022-07-28 14:50 UTC, Im0tec commented on src/App.js
> +        <Route path='/search/:filter/:genderName/:id' element={<FilterTitles/>}/>
não vi kkkkkkkkkkkkk

2022-07-29 23:56 UTC, JoaoWudarski commented on src/components/Homepage/Home/Home.js
> +  },[]);
Deu boa deu boa SóAgradece

2022-08-01 12:36 UTC, Im0tec approved these changes

2022-08-01 12:47 UTC, JoaoWudarski approved these changes

2022-08-01 18:19 UTC, merged