Streaming page
Filmaro/Filmaro pull request #45
Opened 2022-09-14 19:29 UTC by MatheusFrate

# 🎬 Filmaro 🎬 - Pull Request

## Description:
Made a dropdown with streaming options.
Reused the titles page so that it receives the titles of the respective stream chosen in the main page dropdown.

## Type of change:

- [x] New feature (This PR adds a new functionality to the project)
- [ ] Technical debt (This PR improve features already created)
- [ ] Bug fix (This PR covers solving a bug)
- [ ] Documentation (This PR require a documentation update, i.e. the class doc)
- [ ] Issue resolution (This PR solve an github open issue)
[Link to solved Issue](https://github.com/Filmaro/Filmaro/issues/44 )

👩🏽‍💻~ Filmaro Team ~👨🏽‍💻

2022-09-14 22:27 UTC, Im0tec requested changes
Muito bom, porém existem várias pendências:

1. Está faltando completar um objetivo do critério de aceitação que é alterar o ícone de triângulo conforme o estado do dropdown:
dropdown aberto: ícone do triângulo pra cima
dropdown fechado: ícone do triângulo pra baixo
![image](https://user-images.githubusercontent.com/69486662/190273937-49515e9f-0b96-46f4-87c1-095d93219338.png)

2. Na opção do Crunchyroll não retorna nada.

2022-09-14 22:30 UTC, vaaaarlos commented on src/components/FilterTitles/FilterTitles.js
> +
Considere remover as blank lines neste caso

2022-09-14 22:30 UTC, vaaaarlos commented on src/components/Header/Header.js
> +
Considere remover as blank lines neste caso

2022-09-14 22:30 UTC, vaaaarlos commented on src/components/Homepage/HomeTitles/style.css
>  }
Adicione um blank line no final do arquivo

2022-09-14 22:33 UTC, vaaaarlos commented on src/components/Header/Header.js
> +        for(var i = 3; i < responseApi.length; i++) {
Rola usar um map aqui?

2022-09-14 22:34 UTC, Im0tec commented on src/App.js
> +        <Route path='/:filter/:streamingName' element={<FilterTitles/>}/>
Sugestão: ser mais breve nos nomes das variáveis é uma boa, podia ser apenas stream

2022-09-14 22:35 UTC, vaaaarlos requested changes
Changes requested.

2022-09-15 00:39 UTC, JoaoWudarski commented on src/App.js
> +        <Route path='/:filter/:streamingName' element={<FilterTitles/>}/>
E o clean code diz para não economizarmos nas palavras para variáveis kkkkkkk Eu voto para deixar streamingName

2022-09-15 00:39 UTC, JoaoWudarski commented on src/components/FilterTitles/FilterTitles.js
> +      setType('S');
getMovies, e está setando o tipo como S? Kkkk Estava olhando a chamada dessa metodo, e ele só traz as séries mesmo? Se sim, não seria melhor trazer tanto série quanto filme?

2022-09-15 00:39 UTC, JoaoWudarski commented on src/components/FilterTitles/FilterTitles.js
> +      setShowList(series);
Será que fica melhor deixar o results.items direto na linha 54?

2022-09-15 00:39 UTC, JoaoWudarski commented on src/components/Header/Header.js
> +        for(var i = 3; i < responseApi.length; i++) {
Adicionar mais uma pergunta aqui, por que o loop começa em 3?

2022-09-15 00:39 UTC, JoaoWudarski commented on src/components/Header/Header.js
> +          var StreamingSlug = responseApi[i].slug;
Não é muito padrão iniciar o nome de variáveis com letra maiúscula. Representa nome de classes, certo?

2022-09-16 13:58 UTC, MatheusFrate commented on src/App.js
> +        <Route path='/:filter/:streamingName' element={<FilterTitles/>}/>
eu voto em manter, assim como o comentario apagado do meu mano Wu

2022-09-16 14:00 UTC, JoaoWudarski commented on src/App.js
> +        <Route path='/:filter/:streamingName' element={<FilterTitles/>}/>
Slk muito humilde mlk

2022-09-16 15:51 UTC, MatheusFrate commented on src/components/Header/Header.js
> +        for(var i = 3; i < responseApi.length; i++) {
mudei para usar map e filter


> Rola usar um map aqui?

mudei para usar map e filter agr

2022-09-16 15:52 UTC, MatheusFrate commented on src/components/Header/Header.js
> +        for(var i = 3; i < responseApi.length; i++) {
> Adicionar mais uma pergunta aqui, por que o loop começa em 3?

como os dados que estou lendo é os mesmos que aparece na home, eu pego a partir do 3 para que não apareça "nos cinemas e em alta no dropdown de streaming"

2022-09-16 15:54 UTC, MatheusFrate commented on src/components/FilterTitles/FilterTitles.js
> +      setType('S');
justo, mudei para getSeries

2022-09-16 16:20 UTC, MatheusFrate commented on src/components/Header/Header.js
> +        for(var i = 3; i < responseApi.length; i++) {
Resolvido via [3792291](https://github.com/Filmaro/Filmaro/pull/45/commits/37922913491c08f1ce9de571fdd3bf0398adb226)

2022-09-16 16:20 UTC, MatheusFrate commented
> Muito bom, porém existem várias pendências:
> 
> 1. Está faltando completar um objetivo do critério de aceitação que é alterar o ícone de triângulo conforme o estado do dropdown:
>    dropdown aberto: ícone do triângulo pra cima
>    dropdown fechado: ícone do triângulo pra baixo
>    ![image](https://user-images.githubusercontent.com/69486662/190273937-49515e9f-0b96-46f4-87c1-095d93219338.png)
> 2. Na opção do Crunchyroll não retorna nada.

Resolvido via [df0d4a0](https://github.com/Filmaro/Filmaro/pull/45/commits/df0d4a027d26fc34b1841aae39b1520ee0a46347)

2022-09-16 16:22 UTC, MatheusFrate commented on src/components/FilterTitles/FilterTitles.js
> +      setType('S');
Resolvido via [3792291](https://github.com/Filmaro/Filmaro/pull/45/commits/37922913491c08f1ce9de571fdd3bf0398adb226)

2022-09-16 16:32 UTC, vaaaarlos approved these changes

2022-09-16 16:35 UTC, Im0tec approved these changes

2022-09-17 00:56 UTC, JoaoWudarski approved these changes

2022-09-17 01:19 UTC, merged