Feature/fid 10 menu
Filmaro/Filmaro pull request #55
Opened 2022-09-30 19:31 UTC by vitorSanchess

# 🎬 Filmaro 🎬 - Pull Request

## Description:

Delete this message and write a summary of changes that was done on the project right here. If necessary, split the changes in topics.

## Type of change:

Delete this message and use "x" between the square brackets to mark a valid option below.

- [x] New feature (This PR adds a new functionality to the project)
- [ ] Technical debt (This PR improve features already created)
- [ ] Bug fix (This PR covers solving a bug)
- [ ] Documentation (This PR require a documentation update, i.e. the class doc)
- [ ] Issue resolution (This PR solve an github open issue)
[Link to solved Issue](#IssueLinkGoesHere)

## Checklist:

Delete this message and the options that is unnecessary, i.e. the options that are no relate to the changes you made.

- [x] I created a responsive component.
- [x] My changes do not generate a new warning or issue.

👩🏽‍💻~ Filmaro Team ~👨🏽‍💻

2022-09-30 19:41 UTC, Im0tec commented
cade a descrição?

2022-09-30 21:14 UTC, vitorSanchess commented
> cade a descrição?

ta adicionado a descrição patrão

2022-10-01 01:24 UTC, Im0tec requested changes
Booooa, quase que a PR foi do Rolling Stones, n tinha dado npm install deu mó monte de erro.
Tenho algumas alterações pra sugerir:
1ª e mais importante: 
![image](https://user-images.githubusercontent.com/69486662/193377631-bff69b27-7934-4544-b72d-57eeed6743ea.png)
Esse fundo durante o hover ta feião, seria legal manter apenas o cursor como pointer e durante o clique alterar o estado, ou aumentando o ícone ou deixando a cor dele um pouquinho mais leve.

As outras alterações estão abaixo:

2022-10-01 01:47 UTC, MatheusFrate commented on package.json
> +    "react-scripts": "^2.1.3",
eh igual o windows a versão antiga é sempre melhor.
7 > 10

2022-10-01 17:55 UTC, vitorSanchess commented on src/components/Menu/Menu.js
> +            <div className='Menu-Wrapper'>
no header os classNames tavam em upper camel case O.o

2022-10-01 18:46 UTC, MatheusFrate approved these changes

2022-10-01 20:22 UTC, JoaoWudarski approved these changes

2022-10-01 20:23 UTC, Im0tec approved these changes

2022-10-01 20:31 UTC, merged